___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [10]:
np.array([5,5,5,5,5,5,5,5,5,5])

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [14]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [15]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [27]:
np.random.rand(1)

array([0.30796314])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [28]:
np.random.randn(25)

array([-2.13410134,  1.37782904,  0.81617682,  1.42450614, -1.11430361,
       -0.35639606, -1.38798602, -0.18314201, -1.84152039, -0.16159392,
        0.26163631, -2.41808699, -1.25027301, -1.86612252, -1.26868913,
        0.57772866, -0.05302312, -0.00463882, -0.20735668, -0.90747276,
        1.35364232, -0.91604325, -0.21931007, -0.22112475,  1.8544494 ])

#### Create the following matrix:

In [33]:
np.rand

array([0.27309021, 0.68925609, 0.36737946, 0.61100606, 0.36874453,
       0.98080701, 0.7348158 , 0.74501731, 0.44493152, 0.39586479,
       0.21010376, 0.90573587, 0.52145088, 0.70104055, 0.20450438,
       0.01542263, 0.30206734, 0.97231025, 0.27988359, 0.0595185 ,
       0.48483794, 0.08581009, 0.12416421, 0.98072551, 0.90732857,
       0.38185868, 0.09494282, 0.91563338, 0.20437251, 0.1041944 ,
       0.3519096 , 0.37004011, 0.32585013, 0.45715234, 0.36017334,
       0.18785577, 0.97643513, 0.21260789, 0.74293334, 0.83967078,
       0.21282838, 0.50415435, 0.22275308, 0.58933697, 0.73705228,
       0.32207765, 0.60661731, 0.38436207, 0.86915946, 0.8900784 ,
       0.47823278, 0.17580411, 0.13786891, 0.18186892, 0.16841098,
       0.75164431, 0.79272226, 0.29534225, 0.5733395 , 0.28089326,
       0.03055689, 0.40592197, 0.44864326, 0.664301  , 0.44855123,
       0.20795667, 0.05444161, 0.27077906, 0.53613915, 0.41034661,
       0.72522832, 0.53733936, 0.50091613, 0.21272033, 0.24020

#### Create an array of 20 linearly spaced points between 0 and 1:

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [34]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [37]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [38]:
mat[3,4]

20

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [43]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [45]:
mat[4]

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [46]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [48]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [49]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [56]:
mat.sum(0)

array([55, 60, 65, 70, 75])

# Great Job!